# Generated by Django 4.1.3 on 2023-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbox",
            name="has_been_read",
            field=models.BooleanField(
                default=False, verbose_name="Has Been Read"
            ),
        ),
    ]
