# Generated by Django 4.1.3 on 2023-01-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paystack_customer_code",
                    models.CharField(
                        max_length=40, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=20, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=27, verbose_name="Transaction Reference"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount Paid")),
                (
                    "shipping_fee",
                    models.IntegerField(verbose_name="Shipping Fee"),
                ),
                ("sales_tax", models.IntegerField(verbose_name="Sales Tax")),
                (
                    "payment_method",
                    models.CharField(
                        max_length=27, verbose_name="Payment Method"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        max_length=30, verbose_name="Payment Type"
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=27, verbose_name="Currency"),
                ),
                ("paid_at", models.DateTimeField(verbose_name="Paid At")),
                ("created_at", models.DateTimeField(verbose_name="Created At")),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max=100",
                        max_length=100,
                        verbose_name="Ordered Item Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="format: required",
                        null=True,
                        verbose_name="Ordered Item Description",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="format: price of item ordered",
                        verbose_name="Ordered Item Price",
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(
                        help_text="format: quantity of item ordered",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="format: S, M, L, XL, or XXL",
                        max_length=100,
                        null=True,
                        verbose_name="Item Size",
                    ),
                ),
                (
                    "defaultImage",
                    models.CharField(
                        blank=True,
                        help_text="format: required, max=100",
                        max_length=2000,
                        null=True,
                        verbose_name="Ordered Item Default Image",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="format: Y-m-d H:M:S",
                        verbose_name="Date item was ordered",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="format: Y-m-d H:M:S",
                        verbose_name="Date ordered item was last updated",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordered Item",
                "verbose_name_plural": "Ordered Items",
                "ordering": ["-ordered_at"],
            },
        ),
    ]
