# Generated by Django 4.1.3 on 2023-01-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordereditem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordered_items",
                to="orders.order",
                verbose_name="Ordered Items",
            ),
        ),
    ]
