# Generated by Django 4.1.3 on 2023-01-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_order_storehouse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-id"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="ordereditem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_items",
                to="orders.order",
                verbose_name="Ordered Items",
            ),
        ),
        migrations.AlterField(
            model_name="ordereditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Item Owner",
            ),
        ),
        migrations.CreateModel(
            name="Storehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=27,
                        null=True,
                        verbose_name="Transaction Reference",
                    ),
                ),
                (
                    "shipping_fee",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Shipping Fee"
                    ),
                ),
                (
                    "sales_tax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sales Tax"
                    ),
                ),
                (
                    "billing_starts",
                    models.DateTimeField(verbose_name="Billing Starts On"),
                ),
                (
                    "storehouse_billings",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Storehouse Billings",
                    ),
                ),
                (
                    "total_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Amount Paid"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paid At"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storehouse_order",
                        to="orders.order",
                        verbose_name="Storehouse Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storehouse",
                "verbose_name_plural": "Storehouse",
                "ordering": ["-created_at"],
            },
        ),
    ]
