# Generated by Django 4.1.3 on 2023-01-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_options_alter_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storehouse",
            name="billing_starts",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Billing Starts On"
            ),
        ),
    ]
