# Generated by Django 4.1.3 on 2023-01-25 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0006_alter_storehouse_billing_starts"),
    ]

    operations = [
        migrations.AddField(
            model_name="storehouse",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storehouse_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Storehouse Owner",
            ),
            preserve_default=False,
        ),
    ]
