# Generated by Django 4.1.3 on 2023-01-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_storehouse_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storehouse",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storehouse_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Storehouse Owner",
            ),
        ),
    ]
