# Generated by Django 4.1.3 on 2023-01-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_storehouse_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paystack_customer_code",
            field=models.CharField(
                max_length=40, verbose_name="Paystack Customer Code"
            ),
        ),
    ]
