# Generated by Django 4.1.3 on 2023-01-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_paystack_customer_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-paid_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
