# Generated by Django 4.1.3 on 2023-01-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
