# Generated by Django 4.1.3 on 2023-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_shippingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="storehouse",
            name="has_been_paid",
            field=models.BooleanField(
                default=False, verbose_name="Has Been Paid"
            ),
        ),
    ]
