# Generated by Django 4.1.3 on 2023-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_storehouse_has_been_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage_off",
                    models.IntegerField(
                        default=0,
                        help_text="format: how many percent off the total price of items",
                        verbose_name="Percentage Off",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="format: leave blank",
                        max_length=7,
                        null=True,
                        unique=True,
                        verbose_name="Coupon Code",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="format: true = coupon has been used",
                        verbose_name="Coupon Status",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="format: Y-m-d H:M:S",
                        verbose_name="Date coupon was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="format: Y-m-d H:M:S",
                        verbose_name="Date it was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_on"],
            },
        ),
    ]
