# Generated by Django 4.1.3 on 2023-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="is_used",
            field=models.BooleanField(
                default=False,
                help_text="format: true = coupon has been used",
                verbose_name="Has been used? ",
            ),
        ),
    ]
